# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CirctuiDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_circuit', models.CharField(max_length=255)),
                ('Description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=255)),
                ('Description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('facebook', models.URLField()),
                ('Instagram', models.URLField()),
                ('Email', models.EmailField(max_length=254)),
                ('Fax', models.IntegerField()),
                ('Mobile', models.IntegerField()),
                ('Adress', models.CharField(max_length=255)),
                ('img_1', models.ImageField(upload_to='')),
                ('description1', models.TextField()),
                ('img_2', models.ImageField(upload_to='')),
                ('description2', models.TextField()),
                ('img_3', models.ImageField(upload_to='')),
                ('description3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.ImageField(upload_to='')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('bld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circuit.Circuit')),
            ],
        ),
        migrations.CreateModel(
            name='lesinfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prisencharche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_circuit', models.CharField(max_length=255)),
                ('Description', models.TextField(null=True)),
                ('Infos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.lesinfos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='circtuidetail',
            name='Circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuit.Circuit'),
        ),
    ]
