# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
