# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_circuit_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetail',
            name='histoire',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
