# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0004_auto_20171226_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetail',
            name='logo_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
