# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0006_auto_20171226_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetail',
            name='mots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
