# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0007_homedetail_mots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('mots', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homedetail',
            name='mots',
        ),
    ]
