# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0008_auto_20171226_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetail',
            name='histoire',
            field=models.TextField(blank=True, null=True, verbose_name='Mots'),
        ),
    ]
