# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0010_auto_20171226_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetail',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homedetail',
            name='Instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homedetail',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
