# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0011_auto_20171227_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='img',
        ),
    ]
